### ISSUE TITLE
jquery-accessibleMegaMenu.js in this repo breaks the example

### ISSUE THREAD

**Issue by symbiotic** [adobe-accessibility/Accessible-Mega-Menu#72]
i'm trying to use the example menu at the top of the homepage, as a starting point:
https://adobe-accessibility.github.io/Accessible-Mega-Menu/

### **homepage (screenshot):**
![mega menu](https://user-images.githubusercontent.com/5098237/164458845-62ca824c-bc24-42b2-8a98-ca4e49636179.png)

### **homepage but with `jquery-accessibleMegaMenu.js` from this repo (screenshot):**
![mega menu (messed up)](https://user-images.githubusercontent.com/5098237/164461150-4be28064-00f5-49fc-a40f-4206b24f242e.png)

so the formatting gets messed up (and the final HTML is actually also different).

the file `jquery-accessibleMegaMenu.js` on the homepage has some differences like less comments and less code.

- which version is newer?
- can you synchronise the homepage and this repo?

**Comment by symbiotic** [comment]
upon further investigation, the homepage menu broke after the changes made by @maedi. it looks like all these changes were not tested with this menu. for example the settings.panelClass is set after it is found (which does not seem to make sense):

<pre>
<b>topnavitemlink = topnavitem.find("a").first();</b>
<b>topnavitempanel = topnavitem.find('.' + settings.panelClass);</b>
_addUniqueId.call(that, topnavitemlink);
// When sub nav exists.
<b>if (topnavitempanel.length) {</b>
	_addUniqueId.call(that, topnavitempanel);
	// Add attributes to top level link.
	topnavitemlink.attr({
		"role": "button",
		"aria-controls": topnavitempanel.attr("id"),
		"aria-expanded": false,
		"tabindex": 0
	});
	// Add attributes to sub nav.
	topnavitempanel.attr({
		"role": "region",
		"aria-hidden": true
	})
	<b>.addClass(settings.panelClass)</b>
	.not("[aria-labelledby]")
	.attr("aria-labelledby", topnavitemlink.attr("id"));
</pre>

**Comment by majornista** [comment]
Thanks for pointing this out. This should be fixed with https://github.com/adobe-accessibility/Accessible-Mega-Menu/commit/ee1d2e83d38cb7032aa160f1bbc3a4d1eb54196b and https://github.com/adobe-accessibility/Accessible-Mega-Menu/commit/3810000cf87ee36686721bde7e0f11db490c337e.

**Comment by symbiotic** [comment]
There is still a problem, that the menu items on the homepage are not expanding anymore. maybe because [3810000](https://github.com/adobe-accessibility/Accessible-Mega-Menu/commit/3810000cf87ee36686721bde7e0f11db490c337e) is missing, when i do a clone. Thanks for the fast response

**Comment by symbiotic** [comment]
@majornista awesome! thank you
